### ISSUE TITLE
Socket opening multiple connections with React-Native

### ISSUE THREAD

**Issue by massimopibiri** [socketio/socket.io-client#1153]
### You want to:

* report a *bug*

After a lot of research, I started to believe this is a bug:
I built a server with an API. It uses Axios for the un-logged calls and Socket.io for the logged calls. Then I have a website connected to it. And that works perfectly. But I have also an application built in react-native which has a strange behavior: it opens connections on every emit without closing them previous connections. As you can see below, I console.log the websocket.engine.clientsCount on the server. Every time I emit from the phone-application it opens a new connection, finding the server with an increasing number of it.
<img width="546" alt="capture" src="https://user-images.githubusercontent.com/18437806/29495759-afbab6aa-85c5-11e7-80b6-bda33242168b.PNG">

```
On server, I user following versions:
"connect-mongo": "^1.3.2",
"express": "^4.14.1",
"express-session": "^1.12.1",
"jwt-simple": "^0.5.1",
"mongodb": "^2.2.30",
"mongoose": "^4.11.5",
"passport": "^0.3.2",
"passport-jwt": "^2.2.1",
"passport-local": "^1.0.0",
"socket.io": "^1.7.3",
"socketio-jwt": "^4.5.0"
```
Here the code of the API. I removed some code for clarity.
```
const passport = require('passport');
const express = require('express');
const session = require('express-session');
const http = require('http');
const morgan = require('morgan');
const mongoose = require('mongoose');
const socketio = require('socket.io');
const bodyParser = require('body-parser');
const socketioJwt   = require("socketio-jwt"); // da commentare
const Users = require('../models/users');

const passportService = require('./services/passport');

const requireAuth = passport.authenticate('jwt', {session: false});
const requireLogin = passport.authenticate('local', {session: false});
const config = require('./config');

const app = express();
const socketRouter = require('./services/socketRouter');
const MongoStore = require('connect-mongo')(session);

const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost/blablabla';
mongoose.connect(mongoUri);
...
const server = http.Server(app);
const websocket = socketio(server);

// add authorization for jwt-passport when first connection -> https://github.com/auth0/socketio-jwt
websocket.use(socketioJwt.authorize({
  secret: config.secret,
  handshake: true
}));

const sessionMiddleware = session({
  store: new MongoStore({ // use MongoDb to store session (re-using previous connection)
    mongooseConnection: mongoose.connection,
    ttl: (1 * 60 * 60)
  }),
  secret: config.secretSession,
  httpOnly: true,
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 86400000 }
});
app.use(sessionMiddleware);
...
websocket.on('connection', (socket) => {
    Users.findById(socket.decoded_token.sub, function(err, user) {
        if (err) { console.log('the user wasn\'t find in database', err); }
        if (user) {
            socket.join(user._id);
            console.log('Clients connected: ', websocket.engine.clientsCount);

            // ------ PROTECTED EVENTS ------ //
            ...
            // ------------------------------ //

        }

        socket.on('disconnect', ()=> {
          socket.leave(user._id);
          onsole.log('user disconnected');
        });
    });
});
...
```
I won't put the initialisation of the website because it works good.

On mobile application, I user following versions:
```
"react-native": "^0.41.0",
"react-native-keychain": "^1.1.0",
"socket.io-client": "^1.7.3",
"socketio-jwt": "^4.5.0"
```
Here is the innitialisation of the react-native application.
```
import * as Keychain from 'react-native-keychain';
import { BASIC_WS_URL } from '../api';

const io = require('socket.io-client/dist/socket.io');
const socketEvents = require('./events');

exports = module.exports = (store) => {
  Keychain.getGenericPassword().then((credentials) => {
    if (credentials && credentials !== false) {
      const { password } = credentials;
      const websocket = io(BASIC_WS_URL, {
        jsonp: false,
        transports: ['websocket'], // you need to explicitly tell it to use websockets
        query: {
          token: password
        }
      });

      websocket.connect();
      websocket.on('connect', (socket) => {
        console.log('Connected');
      });

      websocket.on('reconnect', (socket) => {
        console.log('Re-connected');
      });

      websocket.on('disconnect', (socket) => {
        console.log('Disconnected');
      });
      // all the events to listen
      socketEvents(websocket, store);
    }
  });
};
```
So... the cause, is it in the package? Thanks

**Comment by massimopibiri** [comment]
It's not a bug. I solved in. I posted the solution here:
https://stackoverflow.com/questions/45610448/socket-io-opening-multiple-connections-with-react-native

**Comment by sitompul** [comment]
Hi @massimopibiri , is there a way to keep the current socket instance (without trying to disconnect it) but still not creating other socket instance.

I'm using socket io as my notification service

**Comment by febinmhd** [comment]
import socketIOClient from 'socket.io-client'
   async componentDidMount(){

          this.socket = socketIOClient('http://192.168.8.118:8000', {
            transports: ['websocket']
          })
}

worked for me

**Comment by iamvucms** [comment]
> import socketIOClient from 'socket.io-client'
> async componentDidMount(){
> 
> ```
>       this.socket = socketIOClient('http://192.168.8.118:8000', {
>         transports: ['websocket']
>       })
> ```
> 
> }
> 
> worked for me

worked for me too
