### ISSUE TITLE
403 Forbidden on POST with Bad handshake method

### ISSUE THREAD

**Issue by zhangzheng7856** [socketio/socket.io-client#1390]
return {"code":2,"message":"Bad handshake method"}

what it mean?

and how can i resolve it?

**Comment by lcherone** [comment]
Check client and server versions are the same

**Comment by darrachequesne** [comment]
@lcherone I don't think that's related to the v3 release, as it was not actually released when the issue was created 5 days ago. Or did that happen with a release candidate version?

@zhangzheng7856 could you please give additional details? Are you using the JS server/client? Which version?

The error is thrown here: https://github.com/socketio/engine.io/blob/4.0.1/lib/server.js#L137

Which means the server receives an HTTP request that is not a GET, but without a sid, which is invalid.

Possibly related: https://github.com/socketio/engine.io-client/issues/636

**Comment by FaustoMendezcom** [comment]
same issue only when using  socket.io-client .  JS server/client are both at 3.0.0
 Server: Express : 4.17.1,
Client: React: 17.0.1
Cors: 2.8.5

Request URL: http://localhost:3000/socket.io/?EIO=4&transport=polling&t=NMWTzIm
Request Method: GET
Status Code: 200 OK
Set-Cookie: io=UOMhQmKogpWnA2zxAAAo; Path=/; HttpOnly; SameSite=Strict
EIO: 4
transport: polling
t: NMWTzIm

96:0{"sid":"UOMhQmKogpWnA2zxAAAo","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}2:40

Request URL: http://localhost:3000/socket.io/?EIO=4&transport=polling&t=NMWTzJm
Request Method: POST
Status Code: 400 Bad Request
EIO: 4
transport: polling
t: NMWTzJm
code: 2, message: "Bad handshake method"}
code: 2
message: "Bad handshake method"

**Comment by travisnguyen20** [comment]
@lcherone You are correct. I have the same issue because the client-side using version 3.0.0 that release 2 days ago while the server-side uses laravel-echo-server that using 2.x.x version.

**Comment by lcherone** [comment]
@travisnguyen20 It happened to me too, had old project which used 2.3.0 which just copied, then when coding the server part I did `npm i socket.io` which installed v3, then spent a few hours debugging why it's broke, then noticed the version diffs, out of a whim changed socket.io-client to match `"socket.io-client": "^3.0.0",` run `npm i` and walla all working again. Thought id look here for the same issue and then posted the suggestion. Think it might catch a few peeps out as error is not at all helpful, and one thing I noticed is that it works just fine in node but will error only when used in the browser.

**Comment by dalexhd** [comment]
Okay... 3 hours with facing this problem xd. My head is literally exploded right now!

So it seems I'm not the only one with this problem right?

**Comment by darrachequesne** [comment]
@dalexhd I'm not sure I understand. Do you have the same version of Socket.IO on both sides?

**Comment by dalexhd** [comment]
Yes the same versión of socket.io client.

**Comment by anselmpaul** [comment]
@darrachequesne I'm hijacking this thread for a similar issue, mentioned here https://github.com/socketio/socket.io-client/issues/1140#issuecomment-728840985. Could you clarify if this is a bug or a breaking change between v2.3 and v3.0?

**Comment by darrachequesne** [comment]
This is indeed a bug. It should be fixed by https://github.com/socketio/engine.io-client/commit/1c8cba8818e930205918a70f05c1164865842a48, included in `engine.io-client@4.0.4` and `socket.io-client@3.0.3` (https://github.com/socketio/socket.io-client/commit/625d146f28376cea88aa8379891d02d845915154#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519).

Can anyone confirm?

**Comment by mcarnoky001** [comment]
I installed version 3.0.3 on client and server, and this issue still persists.

**Comment by mcarnoky001** [comment]
I installed version 3.0.3 on client and server, and this issue still persists.

**Comment by darrachequesne** [comment]
I'm closing this, as I think the issue is now fixed.

@mcarnoky001 could you please open an issue with a reproducing test case? Thanks!
