### ISSUE TITLE
Unrecognized WebSocket connection option(s) `localAddress`. Did you mean to put these under `headers`

### ISSUE THREAD

**Issue by vikasg603** [socketio/socket.io-client#1395]
# You want to:

* [x] report a *bug*

### Current behaviour

```
Receiving Warning as Unrecognized WebSocket connection option(s) `localAddress`. Did you mean to put these under `headers`
```

### Steps to reproduce (if the current behaviour is a bug)

After upgrading socket.io-client to 3.x I am getting this warning while connecting socket.io

### Expected behaviour

There should be no warning

### Setup
- OS: iOS
- browser: React Native
- socket.io version: ^3.0.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
This issue is related https://github.com/socketio/socket.io-client/issues/1290
but it's not what warning I am getting.

**Comment by darrachequesne** [comment]
That's weird, I thought `localAddress` was supported by React Native: https://github.com/socketio/engine.io-client/commit/e5bc1063cc90a7b6262146c7b5338ffff1ff9e5b

Maybe it was removed lately? I didn't find anything in the release notes: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by vikasg603** [comment]
I am using React Native ^0.63.3
On downgrading the version it's working but the issue is with the latest version only.

**Comment by darrachequesne** [comment]
Hmm, I guess that's because the `localAddress` option is behind a `if` in v2: https://github.com/socketio/engine.io-client/blob/3.4.4/lib/transports/websocket.js#L115-L117

I'm digging a bit, to see where the affirmation `Only 'headers' and 'localAddress' options are supported by the WebSocket implementation in React Native.` (in the commit message of https://github.com/socketio/engine.io-client/commit/e5bc1063cc90a7b6262146c7b5338ffff1ff9e5b) can come from.

**Comment by vikasg603** [comment]
Is there any working solution for v3 or i have to use 2.x version only ?

**Comment by darrachequesne** [comment]
This should be fixed in `engine.io-client@4.0.3` (which is included in `socket.io-client@3.0.x`). Could you please confirm?

**Comment by vikasg603** [comment]
No, still the same issue.
I also checked the difference between https://github.com/socketio/engine.io/compare/4.0.2...4.0.3
But I don't think there are any changes other than the package.json.

**Comment by darrachequesne** [comment]
@vikasg603 I'm not able to reproduce: https://github.com/socketio/socket.io/tree/master/examples/react-native

Could you please check your version of `engine.io-client`?

**Comment by vikasg603** [comment]
"engine.io-client": {
			"version": "4.0.3",
			"resolved": "https://registry.npmjs.org/engine.io-client/-/engine.io-client-4.0.3.tgz",
			"integrity": "sha512-2U6dZkOrMGpVh11l+4pMXHMDnirnzIPIYfugEUpnAl0/3wBb+GO7euu0TT3Nn8E5hgaWSpUA+XOfrch2uZdyGA==",
			"requires": {
				"base64-arraybuffer": "0.1.4",
				"component-emitter": "~1.3.0",
				"debug": "~4.1.0",
				"engine.io-parser": "~4.0.1",
				"has-cors": "1.1.0",
				"parseqs": "0.0.6",
				"parseuri": "0.0.6",
				"ws": "~7.2.1",
				"xmlhttprequest-ssl": "~1.5.4",
				"yeast": "0.1.2"
			},


it's 4.0.3

**Comment by vikasg603** [comment]
I tried npm cache clean, and then npm clean install and also react-native clear cache, but same issue.

**Comment by vikasg603** [comment]
Hey @darrachequesne The problem got resolved with version socket.io 3.0.3 and engine.io version 4.0.4
Thanks.
