### ISSUE TITLE
crash on react native android after upgrading to v3

### ISSUE THREAD

**Issue by yanush** [socketio/socket.io-client#1411]
After migrating to socket.io-client 3.0.3 (from v2) I get a crash on my android client (ios client works fine with this version)
The crash seems to be native implementation related:
_Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference_

I init the socket through socket manager this way:

```
this.socketManager = new Manager(urlConnection, {
reconnectionDelay: 500,
reconnectionDelayMax: 500,
timeout: 4000,
});

this.socket = this.socketManager.socket('/');
```
Was anyone able to use v3 client on android?

Env:
socket.io: 3.0.3
socket.io-client: 3.0.3
socket.io-redis: 6.0.1
react-native: 0.63.3

**Comment by darrachequesne** [comment]
Hmm... this should be fixed by https://github.com/socketio/engine.io-client/commit/ccb99e3718e8ee2c50960430d2bd6c12a3dcb0dc.

Could you please check the version of `engine.io-client` that you are using (`npm ls engine.io-client`)?

Duplicate of https://github.com/socketio/socket.io-client/issues/1403

**Comment by yanush** [comment]
the engine.io-client version is 4.0.0 as listed in package.json of socket.io-client dependencies.
I'll try the suggested fix, but I think it would be great if you guys can update the dependencies on the next version of socket.io-client

**Comment by AGurindapalli** [comment]
@darrachequesne @yanush still it's now working on Android.. I have updated engine.io-client to 4.0.4.

**Comment by yanush** [comment]
upgrading engine.io alone didn't help for me, but after uninstalling and reinstalling socket.io-client it was fixed

**Comment by AGurindapalli** [comment]
> upgrading engine.io alone didn't help for me, but after uninstalling and reinstalling socket.io-client it was fixed

Still no luck. Do i need to do any configuration on Android folder??

**Comment by yanush** [comment]
is your client crashing on android or just not connecting?

**Comment by AGurindapalli** [comment]
> is your client crashing on android or just not connecting?

It's not connecting

**Comment by yanush** [comment]
then please open another issue since this one was dealing with android crash
