### ISSUE TITLE
4.3.0 Buffer is not defined

### ISSUE THREAD

**Issue by faradaytrs** [socketio/socket.io-client#1504]
**Describe the bug**

After i compile app in production mode in vite (it uses rollup). I get the following error:
Buffer is not defined at constants.js:5
Socket.IO client version: `4.3.0`

**Platform:**
 - Device: iMac late 2015
 - OS: MacOS

**Additional context**

I use Vercel for compilation, but i think problem is not with Vercel

**Comment by darrachequesne** [comment]
Arf, now that the dev build is fixed (https://github.com/socketio/engine.io-client/commit/49719142f65e23efa65fca4f66765ded5d955972), it's the production build that fails... I'm digging into this.

**Comment by faradaytrs** [comment]
Nope it's still the same. And error is in runtime, not during the build.

**Comment by faradaytrs** [comment]
After I updated dep to use esm it works, but I believe it might be a problem in many cases for many people.

**Comment by Murderlon** [comment]
We are running into this problem when users are building Uppy with Vite: https://github.com/transloadit/uppy/issues/3265. It's currently blocking people from going to production.

I investigated and this seems to be a dual publishing issue. If you import `socket.io-client` in ESM then everything works fine. But if you are importing it indirectly through commonjs, then `socket.io-client` ships `Buffer` to the browser, which will fail.

Here is a minimal reproducible example:

[vite-socketio.zip](https://github.com/socketio/socket.io-client/files/7514379/vite-socketio.zip)
 
**Note**: this zip includes the `node_modules` because I added a `fake-package` folder in there with a `package.json` and `index.js`.

The `index.js` only does this:

```js
const io = require('socket.io-client')

module.exports = io
```

To see the error:

1. Download and extract zip
2. Do **not** run `npm install`
2. `npm run build && npm run preview`
3. See error in the console.

As this is blocking our customers I'm willing to contribute to fix this but I would need some pointers to get started. As far as I know the buffer usage comes from [engine.io-client](https://github.com/socketio/engine.io-client).

**Comment by darrachequesne** [comment]
@Murderlon I could indeed reproduce the issue, thanks a lot for the sample project :+1: 

This should be (finally!) fixed by https://github.com/socketio/engine.io-client/commit/9fcaf58d18c013c0b92fdaf27481f0383efb3658, included in `engine.io-client@6.0.3` and `socket.io-client@4.3.2` by transitivity.
